/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/window.glb
Author: Moon (https://sketchfab.com/Moon_solstice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stargazing-through-the-attic-window-6b3e2a011f024ac6a6b123ed33d0ec28
Title: Stargazing through the attic window ☆
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Window(props) {
  const { nodes, materials } = useGLTF("/models/window.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={50}>
          <mesh
            geometry={nodes.face_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.hair_strands_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.shirt_bands_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.hair_big_chunk_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.hair_small_chunk_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.transparent_shirt_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.polySurface1_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            geometry={nodes.necklace_lambert1_0.geometry}
            material={materials.lambert1}
          />
        </group>
        <mesh
          geometry={nodes.pPlane2_eyelashes_0.geometry}
          material={materials.eyelashes}
          position={[0.18, -2.56, -1.01]}
          rotation={[-0.08, 0, 0]}
        />
        <mesh
          geometry={nodes.pPlane3_eyelashes_0.geometry}
          material={materials.eyelashes}
          position={[0, -0.76, 0.18]}
          rotation={[-0.01, 0, 0]}
        />
        <mesh
          geometry={nodes.pSphere1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.background_background1_0.geometry}
          material={materials.background1}
          position={[-38.83, -18.31, -100.01]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[493.87, 824.07, 246.54]}
        />
        <mesh
          geometry={nodes.MASH1_ReproMesh_particle_0.geometry}
          material={materials.particle}
          scale={0.97}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/window.glb");
